trigger: none

# variables:
#     - name: system.collectionId
#       value: 5f7146e5-9251-4871-bea7-39eda9d40142
#     - name: system.debug
#       value: false 
#     - name: system.definitionId
#       value: 2289            
#     - name: system.teamProject
#       value: Titan_OneMiddleware             
    
stages:
- template: templates/dotnet-build.yml
  parameters: 
    Environment: 'Dev'
    ProjectName: './Example.sln'
    arguments: '--configuration Release --output publish_output'
    verbosity: 'Detailed'
    artifactName: 'drop'

# - template: templates/dotnet-release.yml
#   parameters:
#     Environment: 'Dev'
#     ProjectName: './Example.sln'
#     appName: 'ZWETITNFAPD003'
#     displayName: 'Deploy_Dev'
#     preDeployApprovals: 'true'
#     artifactName: 'drop'
#     connectedServiceNameARM: 'VZI-GX-NP-SUB049 (738ddeb5-7602-4bfb-a123-ac967fb32b6a)'
   
