trigger: none

variables: 
  - group: Titan_OneMiddleware_Functionapp   
parameters:
 - name: Projectname
   displayName: Enter your Projectname
   type: string
 - name: Environment
   displayName: Select Environment
   type: string
   values:
   - Dev
   - QA
   - Prod
 - name: serviceConnection 
   displayName: Service Connection
   type: string
   values: 
   - VZI-GX-NP-SUB049 (738ddeb5-7602-4bfb-a123-ac967fb32b6a)
   
variables:
  - name: DevartifactName
    value: 'dev-artifact'
  - name: Devappname
    value: 'dev-app'
  - name: QAartifactName
    value: 'qa-artifact'
  - name: QAappname
    value: 'qa-app'
  - name: ProdartifactName
    value: 'prod-artifact'
  - name: Prodappname
    value: 'prod-app'   

stages:
- template: templates/dotnet-build.yml
  parameters: 
    Environment: ${{ parameters.Environment }}
    ProjectName: ${{ parameters.Projectname }}
    artifactName: ${{ variables[parameters.Environment + 'artifactName'] }}

- template: templates/dotnet-release.yml
  parameters: 
    Environment: ${{ parameters.Environment }}   
    ProjectName: ${{ parameters.Projectname }}
    appName: $(Devappname)
    artifactName: $(DevartifactName)
    serviceConnection: ${{ parameters.serviceConnection }}
   
